# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BzGDYQL1SVT5i6IBwd7fELtSG0f6wJVz
"""

import streamlit as st
import pandas as pd
import numpy as np

# Judul Aplikasi
st.title("Peta Interaktif Sederhana 🌍")

# 1. Menyiapkan data koordinat (Contoh: area Sumatra Selatan)
data = pd.DataFrame({
    'latitude': [-3.2033, -3.2500, -3.1500],
    'longitude': [104.5768, 104.6000, 104.5500],
    'nama_lokasi': ['Titik A', 'Titik B', 'Titik C']
})

# 2. Opsi untuk mengganti tampilan peta
peta_opsi = st.selectbox(
    'Pilih Tampilan Peta:',
    ('Default', 'Data Titik (st.map)')
)

if peta_opsi == 'Default':
    st.map(data)
    st.write("Menampilkan peta dasar default.")
else:
    st.map(data, latitude='latitude', longitude='longitude')
    st.write("Menampilkan titik kustom yang Anda buat.")